# Generated by Django 5.0.6 on 2024-07-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_salary', models.FloatField()),
                ('employee_phone', models.CharField(max_length=100)),
                ('employee_national_id', models.CharField(max_length=100)),
            ],
        ),
    ]
